name: Locust Performance Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      users:
        description: "Number of users (u)"
        required: false
        default: "10"
      spawn_rate:
        description: "Spawn rate (r)"
        required: false
        default: "2"
      run_time:
        description: "Run time (e.g., 3m, 5m)"
        required: false
        default: "3m"
      host_url:
        description: "Host URL"
        required: false
        default: "https://delvjkninl.sandbox.getos1.com/"

permissions:
  contents: read

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install locust
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Locust Test and Generate Report
        run: |
          LOCUST_USERS=${{ inputs.users || '10' }}
          LOCUST_SPAWN_RATE=${{ inputs.spawn_rate || '2' }}
          LOCUST_RUN_TIME=${{ inputs.run_time || '3m' }}
          LOCUST_HOST=${{ inputs.host_url || 'https://delvjkninl.sandbox.getos1.com/' }}

          locust -f locustfile.py --headless -u $LOCUST_USERS -r $LOCUST_SPAWN_RATE --run-time $LOCUST_RUN_TIME --host=$LOCUST_HOST --html=report.html

      - name: Upload Locust Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: locust-report
          path: report.html
